### ISSUE TITLE
[backend] テストケースが全部表示されている

### ISSUE THREAD

**Issue by earlgray283** [szpp-dev-team/szpp-judge#135]
rpc: `GetContestTask`
`IsSample: true` での絞り込みができていない？

![Screenshot 2023-10-12 at 14 12 04](https://github.com/szpp-dev-team/szpp-judge/assets/43411965/3585ce29-d3a2-4028-a07f-4309ab6c72f5)

**Comment by evipepota** [comment]
今見た　見てみます

**Comment by evipepota** [comment]
↑なんかぶっ壊れたので一回戻しました
